# Generated by Django 4.0.2 on 2022-03-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='slug',
        ),
    ]
