# Generated by Django 4.0.2 on 2022-03-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_sale_availble_product_sale_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_1', models.CharField(max_length=200)),
                ('parameter_2', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_choice',
            field=models.ManyToManyField(to='shop.Product_Choice'),
        ),
    ]
