# Generated by Django 4.0.2 on 2022-03-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_choice_product_product_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product_choice'),
            preserve_default=False,
        ),
    ]
