# Generated by Django 4.0.2 on 2022-03-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_myshop_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myshop',
            name='image_look',
        ),
    ]
