# Generated by Django 4.0.2 on 2022-03-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
