# Generated by Django 3.2.12 on 2022-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='myshop',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='shop.IPAddress', verbose_name='بازدید ها'),
        ),
    ]
