# Generated by Django 3.2.12 on 2022-03-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_final_price_product_last_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.PositiveIntegerField(blank=True, verbose_name='تخفیف'),
        ),
    ]
